## Canary CI/CD
name: Canary
run-name: Canary

on:
  push:
    branches:
      - test-canary-security-fix

jobs:
  test:
    uses: kaltura/playkit-js-common/.github/workflows/cypress.yml@master
    secrets: inherit

  canary:
    if: ${{ github.actor != 'PlaykitJs-Bot' }}
    uses: kaltura/playkit-js-common/.github/workflows/canary_plugin.yaml@test-canary-security-fix
    secrets: inherit
    with:
      schema-type: "playerV3Versions"
      tests-yarn-run-to-execute: 'build eslint'
      node-version: "18.x"
